require("options")
require("plugins")

vim.cmd.colorscheme("habamax")
vim.api.nvim_set_hl(0, "Normal", { bg = "#181818" })
vim.api.nvim_set_hl(0, "FloatNormal", { link = "Normal" })
vim.api.nvim_set_hl(0, "NonText", { bg = "none" })
vim.api.nvim_set_hl(0, "VertSplit", { link = "LineNr" })
vim.api.nvim_set_hl(0, "StatusLine", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "none", bg = "DarkGrey" })
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "Green" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "DarkYellow" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "DarkRed" })
vim.api.nvim_set_hl(0, "TabLine", { fg = "none", bg = "none" })
vim.api.nvim_set_hl(0, "TabLineFill", { fg = "DarkGrey", bg = "none" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "White", bg = "none" })
vim.api.nvim_set_hl(0, "Visual", { link = "CursorLine" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = "orange" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = "red" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = "LightBlue" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = "LightGrey" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineOk", { undercurl = true, sp = "LightGreen" })
vim.api.nvim_set_hl(0, "ModeMsg", {bg = "none", fg = "LightGreen"})
