require("plugins.lazy")
require("plugins.treesitter")
require("plugins.colourscheme").nord()
require("plugins.lsp")

require("plugins.fzf")
require("mini.pairs").setup()
require("mini.trailspace").setup()
require("mini.comment").setup()
require("plugins.oil")
require("plugins.gitsigns")
require("plugins.drop")
